// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationaryBrouchure.Server.Data;

#nullable disable

namespace StationaryBrouchure.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929221116_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationaryBrouchure.Server.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StationaryBrouchure.Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blue",
                            Description = "A blue ink pen.",
                            ImageUrl = "https://via.placeholder.com/150/0000FF/FFFFFF?text=Pen",
                            Name = "Pen",
                            Price = 1.99
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            Description = "A ruled notebook.",
                            ImageUrl = "https://via.placeholder.com/150/FFFFFF/000000?text=Notebook",
                            Name = "Notebook",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            Color = "Yellow",
                            Description = "A wooden pencil.",
                            ImageUrl = "https://via.placeholder.com/150/FFFF00/000000?text=Pencil",
                            Name = "Pencil",
                            Price = 0.98999999999999999
                        },
                        new
                        {
                            Id = 4,
                            Color = "Pink",
                            Description = "A pink rubber eraser.",
                            ImageUrl = "https://via.placeholder.com/150/FF69B4/FFFFFF?text=Eraser",
                            Name = "Eraser",
                            Price = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Color = "Yellow",
                            Description = "A fluorescent yellow highlighter.",
                            ImageUrl = "https://via.placeholder.com/150/FFFF00/000000?text=Highlighter",
                            Name = "Highlighter",
                            Price = 1.49
                        },
                        new
                        {
                            Id = 6,
                            Color = "Assorted",
                            Description = "Colorful sticky notes.",
                            ImageUrl = "https://via.placeholder.com/150/FF6347/FFFFFF?text=Sticky+Notes",
                            Name = "Sticky Notes",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            Color = "Assorted",
                            Description = "Assorted binder clips.",
                            ImageUrl = "https://via.placeholder.com/150/808080/FFFFFF?text=Binder+Clips",
                            Name = "Binder Clips",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Description = "A standard tape dispenser.",
                            ImageUrl = "https://via.placeholder.com/150/000000/FFFFFF?text=Tape+Dispenser",
                            Name = "Tape Dispenser",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 9,
                            Color = "Silver",
                            Description = "A pair of scissors.",
                            ImageUrl = "https://via.placeholder.com/150/C0C0C0/000000?text=Scissors",
                            Name = "Scissors",
                            Price = 3.4900000000000002
                        },
                        new
                        {
                            Id = 10,
                            Color = "Transparent",
                            Description = "A plastic ruler.",
                            ImageUrl = "https://via.placeholder.com/150/FFFFFF/000000?text=Ruler",
                            Name = "Ruler",
                            Price = 1.1899999999999999
                        },
                        new
                        {
                            Id = 11,
                            Color = "Black",
                            Description = "A black permanent marker.",
                            ImageUrl = "https://via.placeholder.com/150/000000/FFFFFF?text=Marker",
                            Name = "Marker",
                            Price = 1.29
                        },
                        new
                        {
                            Id = 12,
                            Color = "Multicolor",
                            Description = "A world globe for reference.",
                            ImageUrl = "https://via.placeholder.com/150/FF4500/FFFFFF?text=Globe",
                            Name = "Globe",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 13,
                            Color = "Brown",
                            Description = "A standard clipboard.",
                            ImageUrl = "https://via.placeholder.com/150/8B4513/FFFFFF?text=Clipboard",
                            Name = "Clipboard",
                            Price = 2.75
                        },
                        new
                        {
                            Id = 14,
                            Color = "Black",
                            Description = "A luxury fountain pen.",
                            ImageUrl = "https://via.placeholder.com/150/000000/FFFFFF?text=Fountain+Pen",
                            Name = "Fountain Pen",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            Id = 15,
                            Color = "White",
                            Description = "An A4 sketch pad.",
                            ImageUrl = "https://via.placeholder.com/150/FFFFFF/000000?text=Sketch+Pad",
                            Name = "Sketch Pad",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 16,
                            Color = "Gray",
                            Description = "A basic calculator.",
                            ImageUrl = "https://via.placeholder.com/150/808080/FFFFFF?text=Calculator",
                            Name = "Calculator",
                            Price = 10.0
                        },
                        new
                        {
                            Id = 17,
                            Color = "Multicolor",
                            Description = "An art set with various colors.",
                            ImageUrl = "https://via.placeholder.com/150/FF69B4/FFFFFF?text=Art+Set",
                            Name = "Art Set",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 18,
                            Color = "Assorted",
                            Description = "A set of colored pencils.",
                            ImageUrl = "https://via.placeholder.com/150/FF6347/FFFFFF?text=Color+Pencils",
                            Name = "Color Pencils",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 19,
                            Color = "White",
                            Description = "A small whiteboard.",
                            ImageUrl = "https://via.placeholder.com/150/FFFFFF/000000?text=Whiteboard",
                            Name = "Whiteboard",
                            Price = 12.5
                        },
                        new
                        {
                            Id = 20,
                            Color = "Assorted",
                            Description = "A set of colored pencils.",
                            ImageUrl = "https://via.placeholder.com/150/FF6347/FFFFFF?text=Color+Pencils",
                            Name = "Color Pencils",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 21,
                            Color = "White",
                            Description = "A small whiteboard.",
                            ImageUrl = "https://via.placeholder.com/150/FFFFFF/000000?text=Whiteboard",
                            Name = "Whiteboard",
                            Price = 12.5
                        });
                });

            modelBuilder.Entity("StationaryBrouchure.Server.Models.CartItem", b =>
                {
                    b.HasOne("StationaryBrouchure.Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
