// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationaryBrouchure.Server.Data;

#nullable disable

namespace StationaryBrouchure.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929001519_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationaryBrouchure.Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blue",
                            Description = "A blue ink pen.",
                            ImageUrl = "images/pen.jpg",
                            Name = "Pen",
                            Price = 1.99
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            Description = "A ruled notebook.",
                            ImageUrl = "images/notebook.jpg",
                            Name = "Notebook",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            Color = "Yellow",
                            Description = "A wooden pencil.",
                            ImageUrl = "images/pencil.jpg",
                            Name = "Pencil",
                            Price = 0.98999999999999999
                        },
                        new
                        {
                            Id = 4,
                            Color = "Pink",
                            Description = "A pink rubber eraser.",
                            ImageUrl = "images/eraser.jpg",
                            Name = "Eraser",
                            Price = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Color = "Yellow",
                            Description = "A fluorescent yellow highlighter.",
                            ImageUrl = "images/highlighter.jpg",
                            Name = "Highlighter",
                            Price = 1.49
                        },
                        new
                        {
                            Id = 6,
                            Color = "Assorted",
                            Description = "Colorful sticky notes.",
                            ImageUrl = "images/sticky-notes.jpg",
                            Name = "Sticky Notes",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            Color = "Assorted",
                            Description = "Assorted binder clips.",
                            ImageUrl = "images/binder-clips.jpg",
                            Name = "Binder Clips",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Description = "A standard tape dispenser.",
                            ImageUrl = "images/tape-dispenser.jpg",
                            Name = "Tape Dispenser",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 9,
                            Color = "Silver",
                            Description = "A pair of scissors.",
                            ImageUrl = "images/scissors.jpg",
                            Name = "Scissors",
                            Price = 3.4900000000000002
                        },
                        new
                        {
                            Id = 10,
                            Color = "Transparent",
                            Description = "A plastic ruler.",
                            ImageUrl = "images/ruler.jpg",
                            Name = "Ruler",
                            Price = 1.1899999999999999
                        },
                        new
                        {
                            Id = 11,
                            Color = "Black",
                            Description = "A black permanent marker.",
                            ImageUrl = "images/marker.jpg",
                            Name = "Marker",
                            Price = 1.29
                        },
                        new
                        {
                            Id = 12,
                            Color = "Multicolor",
                            Description = "A world globe for reference.",
                            ImageUrl = "images/globe.jpg",
                            Name = "Globe",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 13,
                            Color = "Brown",
                            Description = "A standard clipboard.",
                            ImageUrl = "images/clipboard.jpg",
                            Name = "Clipboard",
                            Price = 2.75
                        },
                        new
                        {
                            Id = 14,
                            Color = "Black",
                            Description = "A luxury fountain pen.",
                            ImageUrl = "images/fountain-pen.jpg",
                            Name = "Fountain Pen",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            Id = 15,
                            Color = "White",
                            Description = "An A4 sketch pad.",
                            ImageUrl = "images/sketch-pad.jpg",
                            Name = "Sketch Pad",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 16,
                            Color = "Gray",
                            Description = "A basic calculator.",
                            ImageUrl = "images/calculator.jpg",
                            Name = "Calculator",
                            Price = 10.0
                        },
                        new
                        {
                            Id = 17,
                            Color = "Multicolor",
                            Description = "An art set with various colors.",
                            ImageUrl = "images/art-set.jpg",
                            Name = "Art Set",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 18,
                            Color = "Assorted",
                            Description = "A set of colored pencils.",
                            ImageUrl = "images/color-pencils.jpg",
                            Name = "Color Pencils",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 19,
                            Color = "White",
                            Description = "A small whiteboard.",
                            ImageUrl = "images/whiteboard.jpg",
                            Name = "Whiteboard",
                            Price = 12.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
